### ISSUE TITLE
Add licence from survey metadata to record

### ISSUE THREAD

**Issue by matilda2812** [AtlasOfLivingAustralia/ecodata#581]
Licence information is required for records. 
If no licence is in survey metadata then use default creative commons licence. 
`projectActivity.dataSharingLicense` is where licence type is stored, but this is a url. Need to check that biocache can accept a url in this field and, if not, map to the licence name.

**Comment by temi** [comment]
Peter requested the following properties to each record from projectActivity -
spatialAccuracy, speciesIdentification, temporalAccuracy, nonTaxonomicAccuracy, dataQualityAssuranceMethods

**Comment by matilda2812** [comment]
Which darwin core fields should these properties map to?

**Comment by elywallis** [comment]
@matilda2812 the 'quick' reference guide to Darwin Core terms is here https://dwc.tdwg.org/terms/ 
I don't know what format the data is in for each of the elements listed above (i.e. what data you're expecting to see in each of those fields) - without that it's difficult to give you a clear mapping. However some of the fields mentioned don't look like Darwin Core fields, e.g. dataQualityAssuranceMethods

**Comment by temi** [comment]
These fields have Biocollect specific values. They are - 
```
        methodType -> 'opportunistic', 'systematic'
        spatialAccuracy -> 'low', 'moderate', 'high'
        speciesIdentification -> 'low', 'moderate', 'high', 'na'
        temporalAccuracy -> 'low', 'moderate', 'high'
        nonTaxonomicAccuracy -> 'low', 'moderate', 'high'
        dataQualityAssuranceMethods {Array} ->
            [ "dataownercurated", "subjectexpertverification", "crowdsourcedverification", "recordannotation", "systemsupported", "nodqmethodsused", "na" ]
```

**Comment by matilda2812** [comment]
Thanks Ely, I had a look at the list but I couldn't see obvious corresponding terms. I'm not sure why we need to add these fields to records, because if there is no corresponding dwc field then the values will not appear in the record download or in the ALA.

**Comment by elywallis** [comment]
Hi Matilda, I think that non DwC fields like these will appear in the "Additional Properties" section of the record but they'll have little meaning. The reason fields like these are generally not used and haven't been adopted into Darwin Core is because of the difficulty of 'rating the rater' - i.e. I might say that that temporal accuracy of my records is high but who am I and what expertise do I bring to that rating? There should probably be a bit of a wider discussion about whether or not it's a good idea to share this data across to Biocache -- discussion with Peggy and Nick to start with

**Comment by temi** [comment]
Thanks all. We have decided to put DQ fields in Collectory.
