### ISSUE TITLE
Include project and survey metadata when creating a data resource

### ISSUE THREAD

**Issue by matilda2812** [AtlasOfLivingAustralia/ecodata#584]
Send project metadata and relevant survey metadata when creating a data resource in collectory. 
Also update data resource information when project information is updated.

**Comment by matilda2812** [comment]
**Proposed mapping**
biocollect -> collectory
project.name -> dataresource.name
project.description + project.aim -> dataresource.description
project.site.coordinates -> dataresource.boundingcoordinates
project.licence + extra words? -> dataresource.citation
projectActivity.dataQualityAssuranceMethods -> dataresource.qualityControlDescription

**Comment by pbrenton** [comment]
biocollect -> Data provider

Is the dataresource.boundingcoordinates a bounding box? If so, how do we handle passing complex shapes?

dataresource.citation    This is a tricky one for the reasons Temi mentioned. 

dataresource.qualityControlDescription      
Not sure if there is a size limit to this, but should include appropriately formatted concatenation of the survey type, survey method, survey method url, survey method description, qa methods, qa method description, data management plan info, etc., replicated for each survey. 

Need to consider how best to bundle all of the respective survey metadata and relevant project level metadata so that it can be unpacked and rendered into the collectory appropriately.

**Comment by matilda2812** [comment]
dataresource.boundingcoordinates takes north, south, east and west coordinates. This is the only location information it is possible to send via the collectory api. It is not ideal for complex shapes but biocollect does store extent coordinates which can be used. There is no option to provide more complex shapes. 

dataresource.citation will be project.legalCustodianOrganisation (lastUpdated.year) projectActivity.name dataset. 

project.aim can actually go in the dataresource.purpose field

Given that once the biocollect data resources are cleaned up in collectory, there will be few projects sending data to collectory, I think the above will work well enough and can be manually supplemented if necessary.
