### ISSUE TITLE
Image licence is default regardless of selection

### ISSUE THREAD

**Issue by matilda2812** [AtlasOfLivingAustralia/ecodata#590]
Currently image licence is set as `DEFAULT_LICENCE` (Creative Commons Attribution) regardless of the licence selected. 
This should change to the licence selected by the user, and if no licence is set then use Creative Commons zero as the default. 
The default rights statement also needs to be updated

**Comment by elywallis** [comment]
Hi team, I might be coming into this a bit late. I've been re-writing the "How to cite images in ALA" knowledge base article. Above, you say that the default licence should be CC-zero for images. That's probaby pushing it a bit too far. 
**The default licence (if none is selected by the user) should remain as CC-BY**
There are good reasons for this:
* CC zero is often used to indicate that no copyright applies, or that copyright is being waived. Examples are CC zero used for *data* as there is legal precedent to back up the claim that data per se is not copyrightable
* We cannot make an assumption that copyright is being waived by the photographer just because they failed to set a CC licence on their image
* Photographs, unlike data, are always interpreted to involve a creative act and are thus copyrightable. To make a default of CC zero for photographs would take too many rights away from the copyright holder. 

Sorry to jump in so late but I would strongly recommend that the default licence, if none is set by the user, should be CC-BY. Please get in touch if you want more information

**Comment by temi** [comment]
Chatted with Peter about the license and he agrees. The default license should be "CC-BY-4.0 International"

**Comment by matilda2812** [comment]
Thanks for the feedback- I have now updated the licence to CC-BY 4.0

**Comment by matilda2812** [comment]
Thanks for the feedback- default image licence is now CC BY 4.0

**Comment by elywallis** [comment]
That's great, thanks for making that change
